package com.testniqatsu.bomberman;

public enum BombermanType {
    PLAYER, WALL, BRICK, BOMB, FIRE,
    SPEED_ITEM, BOMB_ITEM, FLAME_ITEM,
    PORTAL, BRICK_BREAK, FLAME_PASS_ITEM,
    GRASS, CORAL, GRASS_BREAK, CORAL_BREAK,
    BALLOOM_E, ONEAL_E, DORIA_E, WALL_BOMB,
    AROUND_WALL
}
